-- Auto generated by rsplug
-- on_ft-local で処理済みの id。2バッファ目以降はこれで定数時間に skip する。
local processed = {}
local pending = {}
local rsplug = require '_rsplug'

-- Keep the ft reverse records in the same retirement path as other triggers.
rsplug.on_loaded(function(id)
	pending[id] = nil
end)
return {
	---@param pkgids string[]
	---@param ft string
	load = function(pkgids, ft)
		for _, id in ipairs(pkgids) do pending[id] = ft end
		local ctl = rsplug
		-- (R3-2) 未処理かつ別トリガで未ロード(ctl.loaded[id] false)のものだけ
		-- new_ids に加える。packadd 成功後に処理済みへ移し、失敗時は retryable にする。
		local new_ids = {}
		for _, id in ipairs(pkgids) do
			if not processed[id] and pending[id] == ft then
				pending[id] = nil
				if not ctl.loaded[id] then
					new_ids[#new_ids + 1] = id
				end
			end
		end
		if #new_ids == 0 then
			return
		end

		local events = { 'Syntax', 'BufEnter', 'BufWinEnter' }
		-- (R3-4) R2 ヘルパで再生用 autocmd をスナップショット。
		local excluded = { ['rsplug.runtime.on_event'] = true }
		local before = ctl.index_autocmds(vim.api.nvim_get_autocmds { event = events }, excluded)

		---新規グループだけ再生する（groupless / 既存グループ追加は次回の自然イベントへ）。
		local function replay_new_groups()
			local discovered = ctl.new_autocmds(vim.api.nvim_get_autocmds { event = events }, before, excluded)
			local replayed = {}
			for _, a in ipairs(discovered) do
				if a.group ~= nil and before.groups[a.group] == nil and replayed[a.group] == nil then
					replayed[a.group] = true
					pcall(vim.api.nvim_exec_autocmds, a.event, { group = a.group, modeline = false })
				end
			end
		end

		local manifest = ctl.manifest
		if manifest.version == 2 and (manifest.runtime or {}).ftplugin ~= nil then
			-- (R3-5) v2 マニフェストで ftplugin パスを解決（runtime lookup 無し）。
			local paths = ctl.get_ft_runtime_files(new_ids, ft)
			-- (R3-6) 新規 id を順に packadd。
			for _, id in ipairs(new_ids) do
				ctl.packadd(id)
				processed[id] = true
			end
			-- (R3-7) 各パスを1回ずつ source（スペース・区切り文字対策で fnameescape）。
			for _, p in ipairs(paths) do
				vim.cmd('source ' .. vim.fn.fnameescape(p))
			end
		else
			-- v1 / 破損 manifest 互換: packadd 前後の runtime 差分で追加ファイルを拾う。
			local before_files = ctl.get_ft_runtime_file(ft)
			for _, id in ipairs(new_ids) do
				ctl.packadd(id)
				processed[id] = true
			end
			local seen = {}
			for _, f in ipairs(before_files) do
				seen[f] = true
			end
			for _, f in ipairs(ctl.get_ft_runtime_file(ft)) do
				if not seen[f] then
					vim.cmd('source ' .. vim.fn.fnameescape(f))
				end
			end
		end

		-- (R3-8) 新規 Syntax/BufEnter/BufWinEnter グループだけ再生。
		replay_new_groups()
	end,
}
