-- Auto generated by rsplug
if vim.g.rsplug_loaded then
	return
end
vim.g.rsplug_loaded = true

local source = debug.getinfo(1, 'S').source
local root = vim.fn.fnamemodify(source:sub(1, 1) == '@' and source:sub(2) or source, ':h')

vim.opt.packpath:prepend(root)

if not vim.o.loadplugins then
	return
end

-- Load rsplug's generated control package now.  This marks package loading as
-- done for startup, so Neovim will not source the same generated plugin files a
-- second time after user init.lua finishes.
vim.cmd.packloadall()

local ok, rsplug = pcall(require, '_rsplug')
if not ok then
	error('[rsplug] failed to load generated runtime: ' .. tostring(rsplug))
end

rsplug.startup()
