-- Auto generated by rsplug
local state = require '_rsplug/on_lua'
local rsplug = require '_rsplug'

-- searcher 自身の参照。package.loaders からの一致検査・削除に使う。
local searcher
-- 再帰ガード: packadd 中に同じ root の require が起きた際の無限ループ防止。
local in_progress = {}
local removal_scheduled = false

---全 root が満足したら、イベントループの次ターンで searcher を package.loaders から
---関数同一性で探して削除する。現在の require 反復中には loader リストを触らない。
local function schedule_removal()
	if removal_scheduled then
		return
	end
	removal_scheduled = true
	vim.schedule(function()
		removal_scheduled = false
		if next(state.remaining_roots) ~= nil then
			return
		end
		for i = #package.loaders, 1, -1 do
			if package.loaders[i] == searcher then
				table.remove(package.loaders, i)
				state.on_packadd = nil
				return
			end
		end
	end)
end

searcher = function(mod_name)
	local mod_root = string.match(mod_name, '^[^./]+')
	-- pending でない root（未登録 or 既に満足）は即 nil。状態は一切変えない。
	if not mod_root or state.remaining_roots[mod_root] == nil then
		return nil
	end
	-- 登録済み root の再帰ロードだけガードする。
	if in_progress[mod_root] then
		return nil
	end
	in_progress[mod_root] = true
	local ok, err = pcall(function()
		for _, id in ipairs(state.luam2pkgid[mod_root] or {}) do
			rsplug.packadd(id)
		end
	end)
	-- 成功・エラー双方でガードを解除し、元のエラーを再送する。
	in_progress[mod_root] = nil
	if not ok then
		error(err, 0)
	end
	if next(state.remaining_roots) == nil then
		schedule_removal()
	end
	-- packadd で既に読み込まれていればそのクロージャを返す。そうでなければ nil を返し、
	-- 標準 loader が新たに追加された runtime path からモジュールを見つける。
	if package.loaded[mod_name] ~= nil then
		local m = package.loaded[mod_name]
		return function()
			return m
		end
	end
	return nil
end

table.insert(package.loaders, 1, searcher)

-- L1: central on_loaded から呼ばれる。pkgid2luam[id] のみを調べて reconcile する。
-- core の packadd 成功末尾から retire_all(id) 経由でこの関数が呼ばれる。
state.on_packadd = function(id)
	if state.reconcile(id) then
		schedule_removal()
	end
end
rsplug.on_loaded(function(id)
	if state.on_packadd then
		state.on_packadd(id)
	end
end)

-- 別トリガで既にロード済みの mapped id を、インストール時に1回だけ reconcile する。
for id, _ in pairs(state.pkgid2luam) do
	if rsplug.loaded[id] then
		state.reconcile(id)
	end
end
if next(state.remaining_roots) == nil then
	schedule_removal()
end
